sudo: required

language: go

go:
  - 1.6

services:
  - docker

before_install:
  # Build and install source-to-image (S2I)
  - pushd /tmp
  - git clone https://github.com/openshift/source-to-image source-to-image
  - cd source-to-image
  - hack/build-go.sh
  - sudo mv _output/local/bin/linux/amd64/* /usr/local/bin
  - popd

script:
  - make test
